### ISSUE TITLE
Importação de dados

### ISSUE THREAD

**Issue by paulohenriquerosa** [mecassauro/RADAR-frontend#9]
A aplicação deve ser capaz de importar a planilha de dados e enviar para o back-end

**Comment by MariaClaudia1328** [comment]
O design pode ser encontrado no [figma](https://www.figma.com/file/W5jbG6Xa5FJMmGp1rfjVjt/Projeto-MecaBauro?node-id=571%3A5) . 

☠️ Fica como sugestão o uso do _dropzone_, segue o [link de um exemplo](https://react-dropzone.js.org/#section-basic-example).
